logging:
  level:
    root: info

server:
  servlet:
    context-path: /app
    port: 8080

spring:
  servlet:
    multipart:
      # default 0
      file-size-threshold: 0MB
      #      location을 설정하지 않으면 System.getProperty("java.io.tmpdir"); 경로에 저장
      location:
      #      default 1MB
      max-file-size: 5MB
      #      default 10MB
      max-request-size: 5MB

  profiles:
    include: app

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            redirect-uri: "https://ssafy-star.com/app/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-name: naver
            client-id: ${oauth2.naver.id}
            client-secret: ${oauth2.naver.secret}
            redirect-uri: "https://ssafy-star.com/app/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
          #              - profile_image
          kakao:
            client-name: kakao
            client-id: ${oauth2.kakao.id}
            client-secret: ${oauth2.kakao.secret}
            redirect-uri: "https://ssafy-star.com/app/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            #              - profile_image
            client-authentication-method: POST
        provider:
          google:
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-info-uri: https://kapi.kakao.com/v2/user/me
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.port}/${mysql.schema}?allowPublicKeyRetrieval=true&useSSL=false&useUniCode=yes&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${mysql.user}
    password: ${mysql.pwd}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.pwd}


const:
  max-star: 15
